data:
  path: 'resources/datasets/'

network:
  - type: 'model-builder'
    name: 'network1'
    vocabulary_size: 10000
    user_count: 6
    learning_rate: 0.5
    embedding_size: 100
    max_title_length: 30
    lstm_neurons: 200
    hidden_neurons: 300
    batch_size: 25
    training_epochs: 5
    users_to_select: 1
    use_l2_loss: false
    l2_factor: 0.01
    use_dropout: false
    dropout_prob: 0.75
    hidden_layers: 0
    use_constant_limit: false
    constant_prediction_limit: 0.3
    trainable_matrix: true
    pre_trained_matrix: 'vectors150d.txt'
    use_pretrained: true
    validation_data: 'validation_data_top_n_single.csv'
    training_data: 'training_data_top_n_single.csv'
    testing_data: 'testing_data_top_n_single.csv'
