csv:
  encoding: 'UTF-8'
  validation_data: 'validation_data_top_n_single.csv'
  training_data: 'training_data_top_n_single.csv'
  testing_data: 'testing_data_top_n_single.csv'

data:
  path: 'resources/datasets/'

network:
  - vocabulary_size: 10000
    user_count: 6
    learning_rate: 0.5
    embedding_size: 100
    max_title_length: 30
    lstm_neurons: 200
    batch_size: 25
    training_epochs: 2
    users_to_select: 1

