data:
  path: 'resources/datasets/'

network:
  - type: 'basic'
    name: 'network1'
    vocabulary_size: 15000
    user_count: 6
    learning_rate: 0.15
    embedding_size: 100
    max_title_length: 25
    lstm_neurons: 300
    batch_size: 25
    training_epochs: 2
    users_to_select: 1
    use_l2_loss: true
    l2_factor: 0.01
    use_dropout: true
    dropout_prob: 0.75
    validation_data: 'validation_data_top_n.csv'
    training_data: 'training_data_top_n.csv'
    testing_data: 'testing_data_top_n.csv'

  - type: 'basic'
    name: 'network2'
    vocabulary_size: 15000
    user_count: 6
    learning_rate: 0.15
    embedding_size: 100
    max_title_length: 25
    lstm_neurons: 300
    batch_size: 25
    training_epochs: 2
    users_to_select: 1
    use_l2_loss: true
    l2_factor: 0.01
    use_dropout: true
    dropout_prob: 0.75
    validation_data: 'validation_data_top_n.csv'
    training_data: 'training_data_top_n.csv'
    testing_data: 'testing_data_top_n.csv'

  - type: 'logloss'
    name: 'network1'
    vocabulary_size: 15000
    user_count: 6
    learning_rate: 0.15
    embedding_size: 100
    max_title_length: 25
    lstm_neurons: 300
    batch_size: 25
    training_epochs: 2
    users_to_select: 1
    use_l2_loss: true
    l2_factor: 0.01
    use_dropout: true
    dropout_prob: 0.75
    validation_data: 'validation_data_top_n.csv'
    training_data: 'training_data_top_n.csv'
    testing_data: 'testing_data_top_n.csv'

  - type: 'logloss/L2'
    name: 'logloss-L2'
    vocabulary_size: 15000
    user_count: 6
    learning_rate: 0.15
    embedding_size: 100
    max_title_length: 25
    lstm_neurons: 300
    batch_size: 25
    training_epochs: 2
    users_to_select: 1
    use_l2_loss: true
    l2_factor: 0.01
    use_dropout: true
    dropout_prob: 0.75
    validation_data: 'validation_data_top_n.csv'
    training_data: 'training_data_top_n.csv'
    testing_data: 'testing_data_top_n.csv'

  - type: 'logloss/L2/1-hidden'
    name: 'logloss-L2-hid1'
    vocabulary_size: 15000
    user_count: 6
    learning_rate: 0.15
    embedding_size: 100
    max_title_length: 25
    lstm_neurons: 300
    batch_size: 25
    training_epochs: 2
    users_to_select: 1
    use_l2_loss: true
    l2_factor: 0.01
    use_dropout: true
    dropout_prob: 0.75
    validation_data: 'validation_data_top_n.csv'
    training_data: 'training_data_top_n.csv'
    testing_data: 'testing_data_top_n.csv'