data:
  path: 'resources/datasets/'

network:
  - type: 'model-builder'
    name: 'network1'
    # Data related configs:
    vocabulary_size: 10000
    user_count: 6
    max_title_length: 30
    validation_data: 'validation_data_top_n_single.csv'
    training_data: 'training_data_top_n_single.csv'
    testing_data: 'testing_data_top_n_single.csv'
    # Embedding matrix configs:
    embedding_size: 150 # Make sure to match pretrained matrix dimensions
    trainable_matrix: true
    use_pretrained: true
    pre_trained_matrix: 'vectors150d.txt'
    # Learning configs:
    learning_rate: 0.5
    training_epochs: 5
    batch_size: 25
    rnn_neurons: 200
    rnn_unit: 'lstm' # Can be 'gru' or 'lstm', default: 'lstm'
    hidden_layers: 0
    hidden_neurons: 300
    use_concat_input: false
    # Regularisation configs:
    use_l2_loss: false
    l2_factor: 0.01
    use_dropout: false
    dropout_prob: 0.75
    # Validation configs:
    use_constant_limit: false
    constant_prediction_limit: 0.3
