data:
  path: 'resources/datasets/'

network:
  - type: 'basic'
    name: 'network1'
    vocabulary_size: 10000
    user_count: 6
    learning_rate: 0.5
    embedding_size: 100
    max_title_length: 30
    lstm_neurons: 200
    batch_size: 25
    training_epochs: 5
    users_to_select: 1
    use_l2_loss: false
    l2_factor: 0.01
    use_dropout: false
    dropout_prob: 0.75
    trainable_matrix: true
    pre_trained_dimension: 50
    pre_trained_matrix: 'glove.6B.50d.txt'
    use_pretrained: true
    validation_data: 'validation_data_top_n_single.csv'
    training_data: 'training_data_top_n_single.csv'
    testing_data: 'testing_data_top_n_single.csv'
