data:
  path: 'resources/datasets/'

network:
  - type: 'basic'
    name: 'network1'
    vocabulary_size: 10000
    user_count: 6
    learning_rate: 0.5
    embedding_size: 100
    max_title_length: 30
    lstm_neurons: 200
    batch_size: 25
    training_epochs: 5
    users_to_select: 1
    validation_data: 'validation_data_top_n_single.csv'
    training_data: 'training_data_top_n_single.csv'
    testing_data: 'testing_data_top_n_single.csv'

  - type: 'basic'
    name: 'network2'
    vocabulary_size: 15000
    user_count: 6
    learning_rate: 1.5
    embedding_size: 100
    max_title_length: 25
    lstm_neurons: 300
    batch_size: 25
    training_epochs: 5
    users_to_select: 1
    validation_data: 'validation_data_top_n_single.csv'
    training_data: 'training_data_top_n_single.csv'
    testing_data: 'testing_data_top_n_single.csv'

  - type: 'logloss'
    name: 'network1'
    vocabulary_size: 15000
    user_count: 6
    learning_rate: 0.15
    training_epochs: 15
    users_to_select: 1
    validation_data: 'validation_data_top_n.csv'
    training_data: 'training_data_top_n.csv'
    testing_data: 'testing_data_top_n.csv'

  - type: 'pretrained_matrix'
    name: 'loggNet1GoodLearningRate'
    vocabulary_size: -1
    user_count: 6
    learning_rate: 0.05
    embedding_size: 100
    max_title_length: 25
    lstm_neurons: 300
    batch_size: 25
    training_epochs: 250
    users_to_select: 1
    validation_data: 'validation_data_top_n_single.csv'
    training_data: 'training_data_top_n_single.csv'
    testing_data: 'testing_data_top_n_single.csv'
    dimensions: 50
    preTrainedFile: 'glove.6B.50d.txt'
    usePretrained: 'Sure'

  - type: 'pretrained_matrix'
    name: 'loggNet2'
    vocabulary_size: -1
    user_count: 6
    learning_rate: 0.05
    embedding_size: 100
    max_title_length: 25
    lstm_neurons: 300
    batch_size: 25
    training_epochs: 250
    users_to_select: 1
    validation_data: 'validation_data_top_n_single.csv'
    training_data: 'training_data_top_n_single.csv'
    testing_data: 'testing_data_top_n_single.csv'
    dimensions: 100
    preTrainedFile: 'glove.twitter.27B.100d.txt'
    usePretrained: 'Sure'

  - type: 'pretrained_matrix'
    name: 'ownvector'
    vocabulary_size: -1
    user_count: 6
    learning_rate: 0.05
    embedding_size: 100
    max_title_length: 25
    lstm_neurons: 300
    batch_size: 25
    training_epochs: 300
    users_to_select: 1
    validation_data: 'validation_data_top_n_single.csv'
    training_data: 'training_data_top_n_single.csv'
    testing_data: 'testing_data_top_n_single.csv'
    dimensions: 100
    preTrainedFile: 'vectors.txt'
    usePretrained: 'Sure'